# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saksham Arora
title: Data Scientist III
email: saksham.arora97@gmail.com

# Social links
github_username: sakshamarora97
linkedin_username: sakshamarora97

# Dark Mode (true/false/never)
darkmode: false

# About Section
about_profile_image: images/profile.jpg
about_content: |
  **I turn data into growth.** Full‑stack data scientist(ML + Product Analytics) with 4+ years' experience shipping ML & analytics that lift revenue, cut churn and scale ops. Signature wins include **↓20 % churn**, **↑4 % revenue**, and **↓30 % fraud noise**.

content:
  - title: Industry Experience
    layout: list
    content:
      - layout: left
        title: WebstaurantStore
        link: https://www.webstaurantstore.com
        sub_title: Data Scientist
        caption: Feb 2024 – Present
        description: |
          - Built churn‑propensity, seasonal‑tagging and learning‑to‑rank models that drove **−20 % subscription churn**, **+15 % trial‑to‑paid**, and **+10 % search engagement**.
          - Productionised pipelines with Spark/BigQuery, FastAPI & MLflow, and shipped self‑service dashboards guiding freemium experiments.
      - layout: left
        title: Paylocity
        link: https://www.paylocity.com
        sub_title: Data Science Intern
        caption: May 2023 – Aug 2023
        description: |
          - Deployed a streaming fraud‑detection service (LightGBM + SHAP on AKS) that cut false‑positive alerts **30 %** and manual review time.

  - title: Earlier Experience (2019 – 2022)
    layout: list
    content:
      - layout: left
        title: Anheuser‑Busch InBev
        link: https://www.ab-inbev.com
        sub_title: Data Scientist I
        caption: Aug 2021 – Mar 2022
        description: |
          - Co‑led assortment‑optimisation & elasticity modelling; causal‑impact tests confirmed **+4 % revenue** across 10 k stores.
          - Improved low‑volume SKU substitution logic, boosting forecast accuracy **10 %**.
      - layout: left
        title: McKinsey & Company
        link: https://www.mckinsey.com
        sub_title: Data Science Consultant
        caption: Mar 2020 – Aug 2021
        description: |
          - Modelled TAM, look‑alike segments & adoption drivers on 200 M+ rows, driving **9–12 %** KPI lifts and informing $4–6 M growth initiatives.
          - Mentored analysts and aligned cross‑functional squads with client OKRs.
      - layout: left
        title: Meesho
        link: https://www.meesho.com
        sub_title: Data Science Consultant
        caption: Mar 2020 – Aug 2021
        description: |
          - Instrumented discovery funnels & ran UI experiments, lifting time‑on‑app **15 %** and CTR **9 %**.
          - Led rollout of screen‑recording analytics that blended qualitative and quantitative insights.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2022 – 2023
        sub_title: MS Analytics
        description: |
          - Coursework in analytical modelling, ML & deep‑learning‑for‑text.
          - Twice selected Graduate TA for “Analytical Modeling.”
      - layout: left
        title: Netaji Subhas Institute of Technology
        caption: 2015 – 2019
        sub_title: B.E. Instrumentation & Control
        description: |
          - Foundation in control systems and signal processing, funfacts - coded basic programs in 8085, learnt about flipflops, time frequency domain and something about 3d integrals!

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: LLM‑assisted Clinical‑Note Scorer
        # link: github.com/sakshamarora97/instruction-tuned-clinical-notes-scoring
        additional_links:
          - title:  sakshamarora97/instruction-tuned-clinical-notes-scoring
            icon: fab fa-github
            url: github.com/sakshamarora97/instruction-tuned-clinical-notes-scoring
        
        quote: >
          Fine‑tuned Tk‑Instruct to automate chart reviews.
        description: |
          ![llm_score](/images/llm_score_awicon.png){: width="150" .center }        
        # description: |
        #   Demonstrates Gen‑AI skill transfer to any text‑heavy domain.

      - layout: top-middle
        title: Outfit Compatibility Scoring
        # link: github.com/sakshamarora97/outfit-compatibility-scoring
        additional_links:
          - title:  sakshamarora97/outfit-compatibility-scoring
            icon: fab fa-github
            url: github.com/sakshamarora97/outfit-compatibility-scoring
        quote: >
          Implemented Outfit Compatibility as a Fill-in-the-blank task, representing categories as Graphs
        description: |
          Used multimodal precomputed embeddings that ranks clothing items by style compatibility on the Polyvore Outfits benchmark.
          ![outfit-compatibility](/images/outfit-compatibility.png){: width="150" .center }        

      - layout: top-middle
        title: Network Monitoring Optimisation
        # link: github.com/sakshamarora97/network-monitoring-optimization
        additional_links:
          - title:  sakshamarora97/network-monitoring-optimization
            icon: fab fa-github
            url: github.com/sakshamarora97/network-monitoring-optimization
        quote: >
          Optimization problem solved using Linear Programming in Gurobi
        description: |
          ![network-optimization](/images/network-optimization.png){: width="150" .center }        
        #   Modeled the problem of placing the minimum amount of sensors in order to detect pipe bursts in a network of pipelines 

      - layout: top-middle
        title: Bayesian Marketing‑Mix Modeling Sandbox
        # link: github.com/sakshamarora97/mmm-sandbox
        additional_links:
          - title:  sakshamarora97/mmm-sandbox
            icon: fab fa-github
            url: github.com/sakshamarora97/mmm-sandbox        
        quote: >
          PyMC pipeline disentangling media spend & seasonality.
        description: |
          Interactive scenario planner; 

  - title: Articles
    layout: list

    content:
      - layout: top-middle
        title: EDA of my Youtube Data
        link: medium.com/@saksham.arora97/exploratory-analysis-of-youtube-watch-history-using-r-db6ecb24e5cd
        quote: >
          Analyzed my youtube watch time data in R! 
        # description: |
        #   Made many mistakes - deep diving in rabbit holes, fitting functions to data just for the sake of it, inefficent code etc.

      - layout: top-middle
        title: Why does Kadane's Algorithm work
        link: medium.com/@saksham.arora97/maximum-sum-subarray-why-does-kadanes-algorithm-work-66f98c072438
        quote: >
          Started leetcoding, really want to go deep on the Maximum Subarry problem 
        # description: |
        #   Deep dived on why Kadane's works, and building an intuition for it

  - title: A Little More About Me
    layout: text
    content: |
      Outside data science I enjoy working out, stand up, hiking, soccer and piano/guitar.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-seo-tag
