# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saksham Arora
title: Data Scientist III
email: saksham.arora97@gmail.com

# Social links
github_username: sakshamarora97
linkedin_username: sakshamarora97

# Dark Mode (true/false/never)
darkmode: false

# About Section
about_profile_image: images/profile.jpg
about_content: |
  **I turn data into growth.** Full‑stack data scientist with 4+ yrs experience shipping ML & analytics that lift revenue, cut churn and scale ops. Signature wins: **↓20 % churn**, **↑4 % revenue**, **↓30 % fraud noise**.

content:
  - title: Industry Experience
    layout: list
    content:
      - layout: left
        title: WebstaurantStore
        link: www.webstaurantstore.com
        sub_title: Data Scientist
        caption: Feb 2024 – Present
        description: |
          - Built churn‑propensity, seasonal‑tagging and learning‑to‑rank models that drove **−20 % subscription churn**, **+15 % trial‑to‑paid**, **+10 % search engagement**.
          - Operationalised pipelines with Spark/BigQuery, FastAPI & MLflow and published self‑service dashboards guiding freemium experiments.
      - layout: left
        title: Paylocity
        link: www.paylocity.com
        sub_title: Data Science Intern
        caption: May 2023 – Aug 2023
        description: |
          - Deployed a streaming fraud‑detection service (LightGBM + SHAP on AKS) that cut false‑positive alerts **30 %** and manual review time.

  - title: Earlier Experience
    layout: text
    content: |
      <details>
      <summary><strong>Click to expand earlier roles</strong></summary>

      **Anheuser‑Busch InBev — Data Scientist I (Aug 2021 – Mar 2022)**  
      • Co‑led assortment optimisation yielding **+4 % revenue** across 10 k stores.  
      • Improved substitution logic ↑10 % forecast accuracy.

      **McKinsey & Company — Data Science Consultant (Mar 2020 – Aug 2021)**  
      • Modelled TAM & adoption drivers on 200 M rows, fueling personalised features worth \$4‑6 M.  
      • Mentored analysts and aligned multi‑disciplinary squads with OKRs.

      **Meesho — Data Science Consultant (Mar 2020 – Aug 2021)**  
      • Instrumented discovery funnels; UI experiments ↑15 % time‑on‑app, ↑9 % CTR.  

      </details>

  - title: Education
    layout: list
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2022 – 2023
        sub_title: MS Analytics
        description: |
          - Coursework in analytical modelling, ML & deep‑learning‑for‑text.  
          - Twice selected Graduate TA for “Analytical Modeling,” honing storytelling.
      - layout: left
        title: Netaji Subhas Institute of Technology
        caption: 2015 – 2019
        sub_title: B.E. Instrumentation and Control
        description: |
          - Foundation in control systems & signal processing underpinning scalable data pipelines.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: LLM‑assisted Clinical‑Note Scorer
        link: https://github.com/sakshamarora97/clinical‑note‑scorer
        quote: >
          Fine‑tuned Tk‑Instruct to extract medically relevant phrases, automating chart reviews.
        description: |
          - Demonstrates Gen‑AI skill transfer to any text‑heavy domain.
      - layout: top-middle
        title: Bayesian Marketing‑Mix Modeling Sandbox
        link: https://github.com/sakshamarora97/mmm‑sandbox
        quote: >
          PyMC pipeline disentangling media spend & seasonality with an interactive scenario planner.
        description: |
          - Shows experimental‑design rigour and end‑to‑end MLOps (Dockerised API, dashboard).

  - title: A Little More About Me
    layout: text
    content: |
      Outside data science I enjoy bouldering, keyboards and improvised jazz.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
