# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2
custom_css:
  - /assets/css/custom.scss
# Personal info
name: Saksham Arora
title: Data Scientist III
email: saksham.arora97@gmail.com

# Social links
github_username: sakshamarora97
linkedin_username: sakshamarora97

# Dark Mode (true/false/never)
darkmode: false

# About Section
about_profile_image: images/profile.jpg
about_content: |
  **I turn data into growth.** Full‑stack data scientist with 4+ yrs experience shipping ML & analytics that lift revenue, cut churn and scale ops. Signature wins: **↓20 % churn**, **↑4 % revenue**, **↓30 % fraud noise**.

content:
  - title: Industry Experience
    layout: list
    content:
      - layout: left
        title: WebstaurantStore
        link: www.webstaurantstore.com
        sub_title: Data Scientist
        caption: Feb 2024 – Present
        description: |
          - Built churn‑propensity, seasonal‑tagging and learning‑to‑rank models that drove **−20 % subscription churn**, **+15 % trial‑to‑paid**, **+10 % search engagement**.
          - Operationalised pipelines with Spark/BigQuery, FastAPI & MLflow and published self‑service dashboards guiding freemium experiments.
      - layout: left
        title: Paylocity
        link: www.paylocity.com
        sub_title: Data Science Intern
        caption: May 2023 – Aug 2023
        description: |
          - Deployed a streaming fraud‑detection service (LightGBM + SHAP on AKS) that cut false‑positive alerts **30 %** and manual review time.

  - title: Earlier Experience
    layout: text
    content: |
      <details class="earlier-experience">
        <summary>Earlier Experience&nbsp;(2019 – 2022)</summary>

        <!-- Job cards below keep exactly the same “layout: left” grid as the main list.
            Just add the utility class .experience-item so the new CSS can grab them. -->

        <div class="experience-item">
          <h3 class="title">Anheuser-Busch InBev <span class="sub_title">Data Scientist I</span></h3>
          <span class="caption">Aug 2021 – Mar 2022</span>
          <ul>
            <li>Co-led assortment-optimisation & elasticity modelling (+4 % revenue across 10 k stores).</li>
            <li>Enhanced low-volume SKU substitution logic, improving forecast accuracy 10 %.</li>
          </ul>
        </div>

        <div class="experience-item">
          <h3 class="title">McKinsey & Company <span class="sub_title">Data Science Consultant</span></h3>
          <span class="caption">Mar 2020 – Aug 2021</span>
          <ul>
            <li>Modelled TAM, look-alike segments & adoption drivers across 200 M+ rows, driving 9–12 % KPI lifts.</li>
            <li>Mentored analysts; kept cross-functional squads aligned with OKRs.</li>
          </ul>
        </div>

        <div class="experience-item">
          <h3 class="title">Meesho <span class="sub_title">Data Science Consultant</span></h3>
          <span class="caption">Mar 2020 – Aug 2021</span>
          <ul>
            <li>Instrumented discovery funnels & ran UI experiments, lifting time-on-app 15 % and CTR 9 %.</li>
          </ul>
        </div>
      </details>

  - title: Education
    layout: list
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2022 – 2023
        sub_title: MS Analytics
        description: |
          - Coursework in analytical modelling, ML & deep‑learning‑for‑text.  
          - Twice selected Graduate TA for “Analytical Modeling,” honing storytelling.
      - layout: left
        title: Netaji Subhas Institute of Technology
        caption: 2015 – 2019
        sub_title: B.E. Instrumentation and Control
        description: |
          - Foundation in control systems & signal processing underpinning scalable data pipelines.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: LLM‑assisted Clinical‑Note Scorer
        link: https://github.com/sakshamarora97/clinical‑note‑scorer
        quote: >
          Fine‑tuned Tk‑Instruct to extract medically relevant phrases, automating chart reviews.
        description: |
          - Demonstrates Gen‑AI skill transfer to any text‑heavy domain.
      - layout: top-middle
        title: Bayesian Marketing‑Mix Modeling Sandbox
        link: https://github.com/sakshamarora97/mmm‑sandbox
        quote: >
          PyMC pipeline disentangling media spend & seasonality with an interactive scenario planner.
        description: |
          - Shows experimental‑design rigour and end‑to‑end MLOps (Dockerised API, dashboard).

  - title: A Little More About Me
    layout: text
    content: |
      Outside data science I enjoy bouldering, keyboards and improvised jazz.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
