# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saksham Arora
title: Data Scientist III
email: saksham.arora97@gmail.com

# Social links
github_username: sakshamarora97
linkedin_username: sakshamarora97

# Dark Mode (true/false/never)
darkmode: false

# About Section
about_profile_image: images/profile.jpg
about_content: |
  **I turn data into growth.** 4‑plus years shipping ML products that boost revenue, cut churn and tame fraud for **e‑commerce, SaaS and finance.**  
  • **20 % ↓ churn** \| **4.2 % ↑ revenue** \| **30 % ↓ false‑positive alerts**  
  Python • SQL • Spark/BigQuery • LightGBM • PyTorch • MLflow • GCP/Azure • Experiment design

content:
  # ———————————————————————————————————————
  - title: Industry Experience
    layout: list
    content:
      - layout: left
        title: WebstaurantStore
        link: https://www.webstaurantstore.com
        sub_title: Data Scientist
        caption: Feb 2024 – Present
        description: |
          - Built a **GBDT churn‑propensity model** (LightGBM, Spark) that **cut subscription churn 20 %** and now **scores 2 M users nightly** via MLflow.
          - Deployed a **learning‑to‑rank search re‑ranker** that lifted CTR 10 % and engagement 15 %.
      - layout: left
        title: Paylocity
        link: https://www.paylocity.com
        sub_title: Data Science Intern
        caption: May 2023 – Aug 2023
        description: |
          - Shipped an Azure/Kubernetes streaming **fraud‑detection service** (LightGBM + SHAP) that trimmed false‑positive alerts and manual reviews 30 %.

  # ———————————————————————————————————————
  - title: |
      <details><summary>Earlier&nbsp;Experience (click to expand)</summary>
    layout: text
    content: |
      <div markdown="1">
      - **Anheuser‑Busch InBev — Data Scientist I** (Aug 2021 – Mar 2022)  
        +4 % revenue across 10 k stores via assortment‑optimisation; 10 % ↑ forecast accuracy with SKU‑substitution logic.
      - **McKinsey & Company — Data Science Consultant** (Mar 2020 – Aug 2021)  
        Modelled TAM & look‑alike segments across 200 M rows, driving 9–12 % KPI lifts; mentored analysts.
      - **Meesho — Data Science Consultant** (Mar 2020 – Aug 2021)  
        UI experiments ↑ time‑on‑app 15 %, CTR 9 %; rolled out screen‑recording analytics tool.
      </div>
      </details>

  # ———————————————————————————————————————
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: LLM‑assisted Clinical‑Note Scorer
        link: https://github.com/sakshamarora97/clinical-note-scorer
        description: |
          - Fine‑tuned **Tk‑Instruct** to surface medically relevant phrases, automating chart reviews; demo Streamlit app lets recruiters play with the model.
      - layout: top-middle
        title: Bayesian Marketing‑Mix Sandbox
        link: https://github.com/sakshamarora97/bayes-mmm
        description: |
          - Open‑sourced a **PyMC pipeline** with scenario planner; illustrates experimental‑design rigour & end‑to‑end MLOps (Docker, FastAPI, dashboards).
      - layout: top-middle
        title: Internal ML Product Accelerators
        description: |
          - Re‑usable notebooks for uplift modelling, search‑ranking features and feature‑store ETL; shorten concept‑to‑deploy time for cross‑functional squads.

  # ———————————————————————————————————————
  - title: Education
    layout: list
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2022 – 2023
        sub_title: MS Analytics
        description: |
          - Coursework in analytical modelling, ML & deep‑learning‑for‑text underpins both marketing experiments and production ML.
      - layout: left
        title: Netaji Subhas Institute of Technology
        caption: 2015 – 2019
        sub_title: B.E. Instrumentation & Control
        description: |
          - Hardware‑meets‑software foundation that informs scalable data pipelines and causal‑impact frameworks.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme
plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
